name: Weather Pipeline CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests psycopg2-binary

      - name: Check Python syntax
        run: |
          python -m compileall scripts

      - name: Create .env
        run: cp docker/.env.example docker/.env

      - name: Inject Weather API Key
        run: |
         echo "WEATHER_API_KEY=${{ secrets.WEATHER_API_KEY }}" >> docker/.env

      - name: Validate Docker Compose
        run: docker compose config